# Railway configuration for monorepo backend
# Working directory is apps/backend

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd apps/backend && npm install --production"]

[start]
cmd = "cd apps/backend && node server.js"

