# Railway configuration for monorepo (backend + frontend)
# Each phase must cd into the appropriate directory since working directory doesn't persist

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "(cd apps/backend && npm install --omit=dev)",
  "(cd apps/frontend && npm install)"
]

[phases.build]
dependsOn = ["install"]
cmds = ["(cd apps/frontend && npm run build)"]

[start]
cmd = "cd apps/backend && NODE_ENV=production node server.js"
